version: "3.1"

services:
  catapult_hans_db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5435:5432"
    volumes:
      - catapult_hans_db:/var/lib/postgresql/data:Z
    container_name: catapult_hans_db
    restart: unless-stopped
volumes:
  catapult_hans_db:
    external: true
